//! THE TOOLS OF THE ASSEMBLY.
use crate::contract::fixtures::Fixture;
use crate::contract::{Class, Context, Entry, Field, Flow, Mode, Outcome, Pick, Tool, When, Words};

/// GROUND: the part with the block clicked with the tool in hand - it is fixed where it stands, the anchor the other
/// parts are placed against. A second click on it lets it go.
pub static GROUND: Tool = Tool {
    id: "assembly.ground",
    flow: Flow::Command,
    title: "jt-ground-btn",
    entries: &[Entry::Button("tb-ground-hint"), Entry::Search("cmdname-ground")],
    other: (Entry::Search("jp-title"), "jp-title"),
    fixture: Fixture::BlockInAssembly,
    picks: &[Pick::Face([20.0, 15.0, 10.0])],
    pick_trial: &[Pick::Face([20.0, 15.0, 10.0])],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Parts { parts: 1, grounded: 1, joints: 0, assemblies: 0 },
    // grounding changes the assembly, not the timeline of a part: it lays no node
    node: "",
    undo: "jt-ground-btn",
    undo_steps: 1,
    stays: true,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/01-components",
    not_applicable: &[
        (2, "the bar of grounding holds no modes: a click fixes a part, a second click lets it go"),
        (5, "grounding takes no value"),
        (6, "grounding takes no value to refuse"),
        (7, "a part is fixed by the click itself: there is nothing to show before it"),
        (8, "grounding is done by the click on the part, as in the professional systems: there is no Apply to press, and the click is point 3"),
        (9, "Esc leaves grounding as \"Done\": what the clicks fixed stays fixed, and taking it back is undo, point 11"),
        (13, "grounding lays no node in a timeline, so there is no row to double-click"),
        (14, "nothing of a timeline stands above an anchor"),
        (15, "an anchor stands on its part alone; deleting the part takes the anchor with it"),
        (16, "grounding belongs to the assembly itself: there is no second place to take it in"),
        (17, "any part can be fixed where it stands: there is nothing the kernel could refuse"),
    ],
};

/// JOINT: the top face of the block of part 1 and the top face of the block of part 2, clicked in turn - a rigid joint
/// between the two parts, laid on the second click as in the professional systems, the tool staying in hand to edit it.
pub static JOINT: Tool = Tool {
    id: "assembly.joint",
    flow: Flow::Command,
    title: "tb-group-joint",
    // the hint of the joint button carries the kind it starts with ("Joint ({ $kind }): ..."), so it is named as the
    // window writes it, with the rigid kind put in
    entries: &[Entry::SearchByArticle, Entry::Button("Joint (Rigid): click an anchor on part A, then on part B. The kind is changed in the bar above [J]")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::TwoBlocksInAssembly,
    picks: &[Pick::Face([20.0, 15.0, 10.0]), Pick::Face([80.0, 15.0, 10.0])],
    pick_trial: &[Pick::Face([20.0, 15.0, 10.0])],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    // the first part becomes the anchor the joint holds the second against, as the professional systems fix the
    // first part of an assembly
    result: Outcome::Parts { parts: 2, grounded: 1, joints: 1, assemblies: 0 },
    // a joint belongs to the assembly, not to the timeline of a part
    node: "",
    undo: "jt-joint-btn",
    undo_steps: 1,
    stays: true,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/02-joints",
    not_applicable: &[
        (2, "the kinds of joint in the bar are not described yet: this contract holds the rigid joint the tool starts with"),
        (5, "the angle and offset in the bar move part B, and the contract does not yet read where a part stands"),
        (6, "the angle and offset in the bar move part B, and the contract does not yet read where a part stands"),
        (13, "a joint lays no node in a part's timeline; it is edited from the list of joints, not by a row of the tree"),
        (14, "nothing of a timeline stands above a joint"),
        (15, "a joint stands on its two parts; deleting one takes the joint with it, which is the parts' matter"),
        (16, "a joint belongs to the assembly it is laid in: there is no second place to take it"),
        (17, "any two faces can be held together rigidly: there is nothing the kernel could refuse"),
    ],
};

/// What the actions of the assembly leave out: nothing is held, nothing is picked, no field.
const MAKES: &[(u8, &str)] = &[
    (2, "an action has no bar of options: its button does the work"),
    (3, "the action takes nothing: it makes"),
    (4, "the action takes nothing, so there is no wrong pick to refuse"),
    (5, "the action has no field"),
    (6, "the action has no field to refuse a value in"),
    (7, "an action is done at once: there is nothing to show before it"),
    (9, "an action is done at once: there is nothing to cancel, only to undo, which is point 11"),
    (13, "a part or a sub-assembly is opened by a double click on its row, which is the tree's own contract"),
    (14, "nothing of a timeline stands above a new part"),
    (15, "a new part stands on the assembly alone"),
    (16, "a part is made in the assembly open around it: there is no second place to take the button in"),
    (17, "an empty part can always be made"),
    (19, "an action is not held, so F1 has no tool in hand to open an article of"),
];

/// NEW_PART: a second part made in the assembly around the block, and stepped into.
pub static NEW_PART: Tool = Tool {
    id: "assembly.new-part",
    flow: Flow::Action,
    title: "hotkey-assembly-n",
    entries: &[Entry::Button("tb-new-part-hint")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::BlockInAssembly,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Parts { parts: 2, grounded: 0, joints: 0, assemblies: 0 },
    node: "",
    undo: "hotkey-assembly-n",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/01-components",
    not_applicable: MAKES,
};

/// NEW_SUBASSEMBLY: a sub-assembly made beside the part with the block, and stepped into.
pub static NEW_SUBASSEMBLY: Tool = Tool {
    id: "assembly.new-subassembly",
    flow: Flow::Action,
    title: "hotkey-assembly-u",
    entries: &[Entry::Button("tb-new-subassembly-hint")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::BlockInAssembly,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Parts { parts: 1, grounded: 0, joints: 0, assemblies: 1 },
    node: "",
    undo: "hotkey-assembly-u",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/01-components",
    not_applicable: MAKES,
};

/// What the patterns and copies of parts leave out: where each copy stands is not read yet.
const COPIES: &[(u8, &str)] = &[
    (3, "the part is picked before the button, and nothing else is clicked"),
    (4, "the part is picked before the button: there is no pick of its own to refuse"),
    (13, "a pattern of parts is reopened from its row of the tree, which stands among the parts, not in a timeline"),
    (14, "nothing of a timeline stands above a pattern of parts"),
    (15, "the pattern stands on its source part; deleting the part takes the pattern with it, which is the parts' matter"),
    (16, "a pattern is made in the assembly open around it: there is no second place to take it"),
    (17, "copies of a part can always be placed"),
];

/// Three parts in a row along X, `v` apart.
fn a_row_along_x(v: f64) -> Outcome {
    Outcome::Row { parts: 3, step: [v, 0.0, 0.0] }
}

/// COMP_LINEAR_PATTERN: the part with the block, picked, repeated three times along X, the spacing typed into its
/// field - at the geometry beside the part and in the bar - and read off where the parts stand.
pub static COMP_LINEAR_PATTERN: Tool = Tool {
    id: "assembly.comp-linear-pattern",
    flow: Flow::Command,
    title: "cmd-comp-lin-array",
    entries: &[Entry::Button("tb-comp-lin-array-hint")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::BlockInAssemblyPicked,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[Field { caption: "f-pitch", by_placeholder: false, when: When::Before, class: Class::Length, typical: 30.0, lo: 0.01, hi: 100000.0, zero: false, negative: false, outcome: a_row_along_x }],
    // a second direction ticked makes a grid: three along X, two along the next axis 30 apart - six parts
    modes: &[&[Mode { word: "cmd-dir2", clicks: None, outcome: Some(Outcome::Parts { parts: 6, grounded: 0, joints: 0, assemblies: 0 }) }]],
    result: Outcome::Row { parts: 3, step: [30.0, 0.0, 0.0] },
    // one operation, one node: the pattern as a whole, as the professional systems keep it
    node: "ComponentPattern",
    undo: "f-comp-array",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/04-arrays",
    not_applicable: &[
        COPIES[0],
        COPIES[1],
        COPIES[2],
        COPIES[3],
        COPIES[4],
        COPIES[5],
        COPIES[6],
    ],
};

/// COMP_CIRCULAR_PATTERN: the same part repeated six times the whole way about the vertical axis.
pub static COMP_CIRCULAR_PATTERN: Tool = Tool {
    id: "assembly.comp-circular-pattern",
    flow: Flow::Command,
    title: "cmd-comp-circ-array",
    entries: &[Entry::Button("tb-comp-circ-array-hint")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::BlockInAssemblyPicked,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Parts { parts: 6, grounded: 0, joints: 0, assemblies: 0 },
    node: "ComponentPattern",
    undo: "f-comp-array",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/04-arrays",
    not_applicable: &[
        (2, "the axis and the whole circle are choices of the bar, and where the copies go is not read yet"),
        (5, "the count is a number of the bar, and the angle opens only with the whole circle off"),
        (6, "the count is a number of the bar, and the angle opens only with the whole circle off"),
        COPIES[0],
        COPIES[1],
        COPIES[2],
        COPIES[3],
        COPIES[4],
        COPIES[5],
        COPIES[6],
    ],
};

/// MIRROR_PART: a mirrored copy of the picked part about the front face of its block - a second part, the left hand of
/// the first.
pub static MIRROR_PART: Tool = Tool {
    id: "assembly.mirror-part",
    flow: Flow::Command,
    title: "mp-title",
    entries: &[Entry::Button("tb-mirror-part-hint")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::BlockInAssemblyPicked,
    picks: &[Pick::Face([20.0, 0.0, 5.0])],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Parts { parts: 2, grounded: 0, joints: 0, assemblies: 0 },
    node: "MirrorPart", // the copy is a node of the timeline: the part that repeats its source mirrored
    undo: "mp-title",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/04-arrays",
    not_applicable: &[
        (2, "the mirrored copy has no modes: a plane or a face is clicked"),
        (5, "the mirrored copy takes no value"),
        (6, "the mirrored copy takes no value to refuse"),
        COPIES[2],
        COPIES[3],
        COPIES[4],
        COPIES[5],
        COPIES[6],
    ],
};

/// INSERT_COMPONENT: the button that brings a STEP, IGES or STL file in as a part - it puts up the chooser of a file
/// to read, in the assembly around the block.
pub static INSERT_COMPONENT: Tool = Tool {
    id: "assembly.insert-component",
    flow: Flow::Action,
    title: "tb-insert-component-hint",
    entries: &[Entry::Button("tb-insert-component-hint")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::BlockInAssembly,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Chooser { save: false },
    node: "",
    undo: "tb-insert-component-hint",
    undo_steps: 0,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/01-components",
    not_applicable: &[
        (2, "the button has no bar of options"),
        (3, "the button takes nothing"),
        (4, "the button takes nothing, so there is no wrong pick to refuse"),
        (5, "the button has no field; the file is picked in the chooser"),
        (6, "the button has no field to refuse a value in"),
        (7, "the chooser comes up at once: there is nothing to show before it"),
        (9, "closing the chooser without a file is the chooser's own matter"),
        (11, "putting up a chooser lays no step of undo"),
        (12, "the chooser waits for an answer; the part it reads is the matter of the formats' round trips"),
        (13, "a button lays no node"),
        (14, "nothing of a timeline stands above a chooser"),
        (15, "a chooser stands on nothing of the document"),
        (16, "a part is inserted into the assembly open around it: there is no second place"),
        (17, "a chooser always comes up"),
        (19, "the button is not held, so F1 has no tool in hand to open an article of"),
    ],
};

/// GROUP: the two parts with their blocks clicked in turn and Enter - held together where they stand, a mate of the
/// kind "Group" and no joint.
pub static GROUP: Tool = Tool {
    id: "assembly.group",
    flow: Flow::Command,
    title: "j-group-made",
    entries: &[Entry::Button("j-group-tip")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::TwoBlocksInAssembly,
    picks: &[Pick::Face([20.0, 15.0, 10.0]), Pick::Face([80.0, 15.0, 10.0])],
    pick_trial: &[Pick::Face([20.0, 15.0, 10.0])],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Mates { kinds: &["Group"] },
    node: "",
    undo: "j-group-made",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/02-joints",
    not_applicable: &[
        (2, "the group has no modes: the parts clicked are the whole of it"),
        (5, "the group takes no value"),
        (6, "the group takes no value to refuse"),
        (7, "the parts do not move: there is nothing to show before Enter but what is picked, which is point 3"),
        (13, "a group is edited from the list of mates, not by a row of a timeline"),
        (14, "nothing of a timeline stands above a group"),
        (15, "a group stands on its parts; deleting one is the parts' matter"),
        (16, "a group belongs to the assembly it is made in: there is no second place to take it"),
        (17, "any parts can be held where they stand: there is nothing the kernel could refuse"),
    ],
};

/// SECTION: the section of the view in the assembly, the top face of the block of its part clicked as the plane - half
/// the assembly is hidden and its inside shows; the document is untouched.
pub static SECTION: Tool = Tool {
    id: "assembly.section",
    flow: Flow::Command,
    title: "sec-btn",
    entries: &[Entry::Button("tb-section-hint")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::BlockInAssembly,
    picks: &[Pick::Face([20.0, 15.0, 10.0])],
    pick_trial: &[Pick::Face([20.0, 15.0, 10.0])],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Section { on: true },
    node: "",
    undo: "tb-section-off",
    undo_steps: 0,
    stays: true,
    upstream: None,
    dependency: None,
    contexts: &[Context::SecondPart],
    refusal: None,
    budget: (10, 2000),
    help: "general/09-viewport",
    not_applicable: &[
        (2, "the section has no modes in the assembly: a plane or a face is the whole of it"),
        (5, "the section takes no value in the assembly"),
        (6, "the section takes no value to refuse"),
        (11, "a section is the view, not the document: it lays no step of undo"),
        (12, "a section is the view, not the document: saving and opening does not carry it"),
        (13, "a section lays no node"),
        (14, "nothing of a timeline stands above a section"),
        (15, "a section stands on nothing of the document"),
        (17, "a plane can always cut the view"),
    ],
};

/// TANGENT: the front face of the block and the side of the shaft clicked in turn and Enter - the shaft rests on the
/// face, a mate of the kind "Tangent" and no joint.
pub static TANGENT: Tool = Tool {
    id: "assembly.tangent",
    flow: Flow::Command,
    title: "j-tangent-made",
    entries: &[Entry::Button("j-tangent-tip")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::BlockAndShaftInAssembly,
    picks: &[Pick::Face([20.0, 0.0, 5.0]), Pick::Face([70.0, 10.0, 5.0])],
    pick_trial: &[Pick::Face([20.0, 0.0, 5.0])],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Mates { kinds: &["Tangent"] },
    node: "",
    undo: "j-tangent-made",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/02-joints",
    not_applicable: &[
        (2, "the tangent has no modes: a plane and a cylinder are the whole of it"),
        (5, "the tangent takes no value: the distance is the radius"),
        (6, "the tangent takes no value to refuse"),
        (13, "a tangent is edited from the list of mates, not by a row of a timeline"),
        (14, "nothing of a timeline stands above a mate"),
        (15, "a mate stands on its parts; deleting one is the parts' matter"),
        (16, "a mate belongs to the assembly it is made in: there is no second place to take it"),
        (17, "two planes, not a plane and a cylinder, are refused by the picks in words - that is point 4"),
    ],
};

/// WIDTH: the right faces of the two walls, then the top of the tab, and Enter - the tab is set midway between the two
/// walls, a mate of the kind "Width" and no joint.
pub static WIDTH: Tool = Tool {
    id: "assembly.width",
    flow: Flow::Command,
    title: "j-width-made",
    entries: &[Entry::Button("j-width-tip")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::TwoWallsAndATab,
    picks: &[Pick::Face([10.0, 15.0, 5.0]), Pick::Face([60.0, 15.0, 5.0]), Pick::Face([25.0, 15.0, 10.0])],
    pick_trial: &[Pick::Face([10.0, 15.0, 5.0])],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Mates { kinds: &["Width"] },
    node: "",
    undo: "j-width-made",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/02-joints",
    not_applicable: &[
        (2, "the width has no modes: two walls and a part are the whole of it"),
        (5, "the width takes no value: the middle is where it puts the part"),
        (6, "the width takes no value to refuse"),
        (13, "a width is edited from the list of mates, not by a row of a timeline"),
        (14, "nothing of a timeline stands above a mate"),
        (15, "a mate stands on its parts; deleting one is the parts' matter"),
        (16, "a mate belongs to the assembly it is made in: there is no second place to take it"),
        (17, "walls that are not parallel are refused by the picks in words - that is point 4"),
    ],
};

/// RELATION: the two hinges clicked in the list of mates and Enter - a gear relation 1:1 ties their turns, a mate of
/// the kind "Gear" beside the two joints.
pub static RELATION: Tool = Tool {
    id: "assembly.relation",
    flow: Flow::Command,
    title: "j-relation-btn",
    entries: &[Entry::Button("j-relation-tip")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::TwoHingesInAssembly,
    picks: &[Pick::Listed("Revolute 1"), Pick::Listed("Revolute 2")],
    pick_trial: &[Pick::Listed("Revolute 1")],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Mates { kinds: &["Gear"] },
    node: "",
    undo: "j-relation-made",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/07-relations",
    not_applicable: &[
        (2, "the kinds of relation in the bar are not described yet: this contract holds the gear the tool starts with"),
        (5, "the ratio in the bar is a number dragged, not a field typed at the geometry, and it moves no part at rest"),
        (6, "the ratio in the bar is a number dragged, not a field typed at the geometry"),
        (13, "a relation is edited from the list of mates, not by a row of a timeline"),
        (14, "nothing of a timeline stands above a mate"),
        (15, "a relation stands on its two mates; deleting one is the mates' matter"),
        (16, "a relation belongs to the assembly it is made in: there is no second place to take it"),
        (17, "a hinge without the degree a kind needs is refused by the pick in words - that is point 4"),
    ],
};

/// INTERFERENCE: the check of the tree switched on over two blocks that run 6000 mm^3 into each other - the tree says
/// there is one interference.
pub static INTERFERENCE: Tool = Tool {
    id: "assembly.interference",
    flow: Flow::Action,
    title: "tree-interference",
    entries: &[Entry::Label("tree-interference")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::TwoBlocksOverlapping,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::OnScreen { word: "Interferences: 1" },
    node: "",
    undo: "tree-interference",
    undo_steps: 0,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/05-interference",
    not_applicable: &[
        (2, "the check is a box of the tree: it has no bar of options"),
        (3, "the check takes nothing: it looks at every part of the assembly"),
        (4, "the check takes nothing, so there is no wrong pick to refuse"),
        (5, "the check has no field"),
        (6, "the check has no field to refuse a value in"),
        (7, "the check shows at once: there is nothing to show before it"),
        (9, "the check is taken back by the same box, which is point 1"),
        (11, "the check is what the window shows, not the document: it lays no step of undo"),
        (12, "the check is what the window shows, not the document: saving and opening does not carry it"),
        (13, "the check lays no node"),
        (14, "nothing of a timeline stands above the check"),
        (15, "the check stands on nothing of the document"),
        (16, "the box is the tree's own: there is no second place to take it"),
        (17, "any parts can be checked: there is nothing the kernel could refuse"),
        (19, "a box is not held, so F1 has no tool in hand to open an article of"),
    ],
};

/// The second part turned by the angle typed into its hinge.
fn second_part_turned(v: f64) -> Outcome {
    Outcome::Turned { part: 1, degrees: v }
}

/// DRIVE: the first hinge clicked in the list of mates and its angle typed - the second part turns by it about the
/// hinge, the number held by the mate.
pub static DRIVE: Tool = Tool {
    id: "assembly.drive",
    flow: Flow::Action,
    title: "j-angle-lower",
    entries: &[Entry::Label("Revolute 1")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::TwoHingesInAssembly,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[Field { caption: "j-angle-lower", by_placeholder: false, when: When::After, class: Class::Angle, typical: 90.0, lo: -180.0, hi: 180.0, zero: true, negative: true, outcome: second_part_turned }],
    modes: &[],
    result: Outcome::Turned { part: 1, degrees: 90.0 },
    node: "",
    undo: "status-edit-joint",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/03-limits-drives",
    not_applicable: &[
        (2, "a mate taken in the list has no bar of options: its numbers stand in the list"),
        (3, "the mate is taken by its row, which is the way in"),
        (4, "the row takes nothing more, so there is no wrong pick to refuse"),
        (6, "without limits every angle is a place of the hinge: an angle past a turn is the same angle, nothing to refuse"),
        (7, "the part turns as the number is typed: there is nothing to show before it"),
        (9, "the number is taken back by undo, which is point 11"),
        (13, "a mate lays no node; it is taken again by its row, which is point 1"),
        (14, "nothing of a timeline stands above a mate"),
        (15, "a mate stands on its two parts; deleting one is the parts' matter"),
        (16, "a mate belongs to the assembly it is made in: there is no second place to take it"),
        (17, "any angle turns a free hinge: there is nothing the kernel could refuse"),
        (19, "a row is not held, so F1 has no tool in hand to open an article of"),
    ],
};

/// BREAK_REF: the cross beside the reference in the properties of the second part - its sketch on the face of the first
/// freezes as a snapshot, and the program says one sketch stopped following the neighbour.
pub static BREAK_REF: Tool = Tool {
    id: "assembly.break-ref",
    flow: Flow::Action,
    title: "comp-break-ref-hint",
    entries: &[Entry::Button("comp-break-ref-hint")],
    other: (Entry::Button("tb-ground-hint"), "jt-ground-btn"),
    fixture: Fixture::PartOnNeighbourFace,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[],
    fields: &[],
    modes: &[],
    result: Outcome::Says { text: "The external reference is broken: 1 sketch(es)" },
    node: "",
    undo: "cmdname-break-ref",
    undo_steps: 1,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "assembly/06-external-refs",
    not_applicable: &[
        (2, "the cross has no bar of options: it breaks the one reference it stands beside"),
        (3, "the reference is taken by where the cross stands, which is the way in"),
        (4, "the cross takes nothing, so there is no wrong pick to refuse"),
        (5, "breaking takes no value"),
        (6, "breaking takes no value to refuse"),
        (7, "breaking is done at once: there is nothing to show before it"),
        (9, "breaking is done at once: there is nothing to cancel, only to undo, which is point 11"),
        (13, "breaking lays no node; the frozen sketch is the sketch's own matter"),
        (14, "nothing of a timeline stands above a broken reference"),
        (15, "the reference stands on the face of the neighbour; deleting it is the neighbour's matter"),
        (16, "the cross stands in the properties of the part alone: there is no second place to take it"),
        (17, "a live reference can always be frozen: there is nothing the kernel could refuse"),
        (19, "a cross is not held, so F1 has no tool in hand to open an article of"),
    ],
};

/// What the search of the tree leaves of the block: the rows whose names begin with the words typed.
fn tree_searched(text: &str) -> Outcome {
    match text {
        "Sketch" => Outcome::TreeRows { shown: &["Sketch 1"], hidden: &["Extrude"] },
        _ => Outcome::TreeRows { shown: &["Extrude"], hidden: &["Sketch 1"] },
    }
}

/// SEARCH: the search box above the tree clicked and "Extr" typed on the block - the extrusion stays in the tree,
/// the sketch under it goes out of sight.
pub static SEARCH: Tool = Tool {
    id: "tree.search",
    flow: Flow::Action,
    title: "tree-search",
    entries: &[Entry::Label("tree-search")],
    other: (Entry::Button("tb-mirror-body-hint"), "cmd-mirror"),
    fixture: Fixture::Block,
    picks: &[],
    pick_trial: &[],
    wrong_picks: &[],
    words: &[Words { caption: "tree-search", by_placeholder: true, typical: "Extr", valid: &["Extr", "Sketch"], invalid: &[], outcome: tree_searched, enter: false }],
    fields: &[],
    modes: &[],
    result: Outcome::TreeRows { shown: &["Extrude"], hidden: &["Sketch 1"] },
    node: "",
    undo: "tree-search",
    undo_steps: 0,
    stays: false,
    upstream: None,
    dependency: None,
    contexts: &[],
    refusal: None,
    budget: (10, 2000),
    help: "general/02-tree",
    not_applicable: &[
        (2, "the search is a box of the tree: it has no bar of options"),
        (3, "the search takes nothing: it looks at every row"),
        (4, "the search takes nothing, so there is no wrong pick to refuse"),
        (5, "the search takes words, not a value: its words are point 5 of the words"),
        (6, "any words are a search: an empty box shows the whole tree, nothing to refuse"),
        (7, "the tree narrows as the words are typed: there is nothing to show before it"),
        (9, "the search is taken back by the cross that clears it"),
        (11, "the search is what the window shows, not the document: it lays no step of undo"),
        (12, "the search is what the window shows, not the document: saving and opening does not carry it"),
        (13, "the search lays no node"),
        (14, "nothing of a timeline stands above the search"),
        (15, "the search stands on nothing of the document"),
        (16, "the box is the tree's own: there is no second place to take it"),
        (17, "any words can be looked for: there is nothing the kernel could refuse"),
        (19, "a box is not held, so F1 has no tool in hand to open an article of"),
    ],
};
